services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: glv-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
      - redis

  reverb:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    command: php artisan reverb:start --host=0.0.0.0 --port=8081
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
      - redis
    ports:
      - "8081:8081"

  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - reverb

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: glv
      POSTGRES_USER: glv
      POSTGRES_PASSWORD: glv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
